version: "3.9"

services:
  server:
    build:
      dockerfile: Dockerfile
    container_name: audio_into_text
    volumes:
      - ./app/:/app/
      - ./ml_models/:/ml_models/
      - ./video/:/video/
      - ./audio/:/audio/
    env_file:
      - .env
    restart: always
    user: aypa:aypa

  nginx:
    image: nginx:latest
    ports:
      - 8010:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/staticfiles:/app/staticfiles
    depends_on:
      - server
