# Generated by Django 5.0.6 on 2024-07-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.IntegerField(verbose_name="Day")),
                ("action_name", models.CharField(max_length=255, verbose_name="Action Name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("video_url", models.URLField(blank=True, null=True, verbose_name="Video URL")),
                ("audio_url", models.URLField(blank=True, null=True, verbose_name="Audio URL")),
                ("transcript", models.TextField(blank=True, null=True, verbose_name="Transcript")),
                ("translated_text", models.TextField(blank=True, null=True, verbose_name="Translated Text")),
            ],
        ),
    ]
