# Generated by Django 5.0.6 on 2024-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_to_text", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translator",
            name="set_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Set Name"),
        ),
        migrations.AlterField(
            model_name="translator",
            name="day",
            field=models.IntegerField(blank=True, null=True, verbose_name="Day"),
        ),
    ]
