# Generated by Django 5.0.6 on 2024-07-08 12:26

import media_to_text.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_to_text", "0002_translator_set_name_alter_translator_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translator",
            name="audio_url",
        ),
        migrations.RemoveField(
            model_name="translator",
            name="video_url",
        ),
        migrations.AddField(
            model_name="translator",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to=media_to_text.models.upload_audio_to, verbose_name="Audio URL"
            ),
        ),
        migrations.AddField(
            model_name="translator",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=media_to_text.models.upload_video_to, verbose_name="Video URL"
            ),
        ),
    ]
